"""Bounded, offline checks for local links in Markdown.

This is a deliberately small Markdown parser, not a complete CommonMark renderer.
It understands inline and reference links/images, balanced destination parentheses,
single-line reference definitions, ATX/setext headings, and HTML id/name anchors.
Fenced code, inline code, and HTML comments are excluded. Heading slugs approximate
GitHub's Unicode-aware rules, including duplicate suffixes; renderer-specific heading
attributes, HTML blocks, deeply nested block quotes/lists, multiline definitions,
and anchors generated by documentation plugins are not interpreted. External URLs
are never fetched. Anchors are checked only in Markdown files; directory links do
not implicitly select a README. Files larger than 1 MiB are not parsed. Pathological
syntax that exceeds a linear parsing-work budget is skipped with a LINK005 warning.
"""

from __future__ import annotations

from dataclasses import dataclass
from html import unescape
from pathlib import Path
import posixpath
import re
import stat
import unicodedata
from urllib.parse import unquote

from .models import Finding


MAX_MARKDOWN_BYTES = 1024 * 1024
MARKDOWN_SUFFIXES = {".md", ".markdown", ".mdown", ".mkd", ".mkdn"}
_ESCAPE = re.compile(r"\\([!\"#$%&'()*+,\-./:;<=>?@\[\]^_`{|}~\\])")
_SCHEME = re.compile(r"^[A-Za-z][A-Za-z0-9+.-]*:")
_DEFINITION = re.compile(r"^ {0,3}\[([^\]\n]+)\]:[ \t]*(.*)$")
_HTML_ANCHOR = re.compile(r"\b(?:id|name)\s*=\s*", re.IGNORECASE)


@dataclass(frozen=True)
class _Link:
    destination: str
    line: int


@dataclass(frozen=True)
class _Document:
    links: list[_Link]
    anchors: set[str]


class _ComplexMarkdown(Exception):
    pass


class _Budget:
    def __init__(self, size: int):
        self.remaining = size * 12 + 10_000

    def spend(self, amount: int = 1) -> None:
        self.remaining -= amount
        if self.remaining < 0:
            raise _ComplexMarkdown


def _blank(text: str) -> str:
    """Mask content without changing offsets or line numbers."""
    return "".join("\n" if char == "\n" else " " for char in text)


def _mask_blocks(text: str) -> str:
    result: list[str] = []
    fence_char = ""
    fence_size = 0
    for line in text.splitlines(keepends=True):
        # One or more blockquote markers are common around fenced examples.
        candidate = re.sub(r"^(?: {0,3}>[ \t]?)+", "", line)
        if fence_char:
            if re.match(r"^ {0,3}" + re.escape(fence_char) + "{" + str(fence_size) + r",}[ \t]*\r?$", candidate.rstrip("\n")):
                fence_char = ""
            result.append(_blank(line))
            continue
        fence = re.match(r"^ {0,3}(`{3,}|~{3,})(.*)$", candidate.rstrip("\r\n"))
        if fence and not (fence[1][0] == "`" and "`" in fence[2]):
            fence_char, fence_size = fence[1][0], len(fence[1])
            result.append(_blank(line))
        else:
            result.append(line)
    # Comments inside fenced examples must not hide the real document after them.
    return re.sub(r"<!--[\s\S]*?(?:-->|\Z)", lambda match: _blank(match[0]), "".join(result))


def _mask_inline_code(text: str) -> str:
    result = list(text)
    runs = [(match.start(), match.end()) for match in re.finditer(r"`+", text)]
    next_run: dict[int, int] = {}
    last_length: dict[int, int] = {}
    for index in range(len(runs) - 1, -1, -1):
        start, end = runs[index]
        length = end - start
        if length in last_length:
            next_run[index] = last_length[length]
        last_length[length] = index
    index = 0
    while index < len(runs):
        start, end = runs[index]
        escape = start - 1
        while escape >= 0 and text[escape] == "\\":
            escape -= 1
        if (start - escape - 1) % 2 or index not in next_run:
            index += 1
            continue
        closing = next_run[index]
        finish = runs[closing][1]
        result[start:finish] = _blank(text[start:finish])
        index = closing + 1
    return "".join(result)


def _reference_key(text: str) -> str:
    return " ".join(_ESCAPE.sub(r"\1", text).split()).casefold()


def _destination(text: str, start: int = 0, budget: _Budget | None = None) -> tuple[str, int] | None:
    """Read a destination, leaving any whitespace/title/closing paren unconsumed."""
    position = start
    while position < len(text) and text[position].isspace():
        if budget:
            budget.spend()
        position += 1
    begin = position
    if position < len(text) and text[position] == "<":
        position += 1
        begin = position
        while position < len(text):
            if budget:
                budget.spend()
            if text[position] == "\\":
                position += 2
                continue
            if text[position] == ">":
                return text[begin:position], position + 1
            if text[position] in "\r\n<":
                return None
            position += 1
        return None
    nesting = 0
    while position < len(text):
        if budget:
            budget.spend()
        char = text[position]
        if char == "\\" and position + 1 < len(text):
            position += 2
            continue
        if char == "(":
            nesting += 1
        elif char == ")":
            if nesting == 0:
                break
            nesting -= 1
        elif char.isspace():
            break
        position += 1
    if nesting:
        return None
    return text[begin:position], position


def _bracket_pairs(text: str) -> dict[int, int]:
    """Match brackets once, including malformed inputs with many unmatched opens."""
    pairs: dict[int, int] = {}
    stack: list[int] = []
    position = 0
    while position < len(text):
        if text[position] == "\\":
            position += 2
            continue
        if text[position] == "[":
            stack.append(position)
        elif text[position] == "]" and stack:
            pairs[stack.pop()] = position
        position += 1
    return pairs


def _inline_end(text: str, position: int, budget: _Budget | None = None) -> int | None:
    """Accept a closing paren, optionally following one Markdown title."""
    had_space = position < len(text) and text[position].isspace()
    while position < len(text) and text[position].isspace():
        if budget:
            budget.spend()
        position += 1
    if position < len(text) and text[position] == ")":
        return position + 1
    if not had_space or position >= len(text) or text[position] not in "\"'(":
        return None
    close = ")" if text[position] == "(" else text[position]
    position += 1
    while position < len(text):
        if budget:
            budget.spend()
        if text[position] == "\\":
            position += 2
            continue
        if text[position] == close:
            position += 1
            while position < len(text) and text[position].isspace():
                if budget:
                    budget.spend()
                position += 1
            return position + 1 if position < len(text) and text[position] == ")" else None
        position += 1
    return None


def _links(text: str, budget: _Budget) -> list[_Link]:
    references: dict[str, str] = {}
    lines = text.splitlines(keepends=True)
    for index, line in enumerate(lines):
        definition = _DEFINITION.match(line.rstrip("\r\n"))
        if definition:
            parsed = _destination(definition[2], budget=budget)
            if parsed:
                references.setdefault(_reference_key(definition[1]), parsed[0])
                lines[index] = _blank(line)
    text = "".join(lines)
    pairs = _bracket_pairs(text)
    found: list[_Link] = []
    pending = [(0, len(text), 1)]
    while pending:
        position, stop, line_number = pending.pop()
        while position < stop:
            budget.spend()
            if text[position] == "\n":
                line_number += 1
            if text[position] == "\\":
                line_number += text[position:position + 2].count("\n")
                position += 2
                continue
            end = pairs.get(position)
            if text[position] != "[" or end is None or end >= stop:
                position += 1
                continue
            following = end + 1
            destination = None
            consumed = following
            if following < stop and text[following] == "(":
                parsed = _destination(text, following + 1, budget)
                if parsed:
                    closing = _inline_end(text, parsed[1], budget)
                    if closing is not None and closing <= stop:
                        destination, consumed = parsed[0], closing
            elif following < stop and text[following] == "[":
                reference_end = pairs.get(following)
                if reference_end is not None and reference_end < stop:
                    key_start, key_stop = (following + 1, reference_end) if reference_end > following + 1 else (position + 1, end)
                    budget.spend(key_stop - key_start)
                    destination = references.get(_reference_key(text[key_start:key_stop]))
                    consumed = reference_end + 1
            elif references:
                budget.spend(end - position)
                destination = references.get(_reference_key(text[position + 1:end]))
            if destination is not None:
                found.append(_Link(destination, line_number))
                # Iterative label traversal handles linked images without recursion.
                pending.append((position + 1, end, line_number))
                budget.spend(consumed - position)
                line_number += text[position:consumed].count("\n")
                position = consumed
            else:
                position += 1
    return found


def _html_tags(text: str):
    position = 0
    while position < len(text):
        start = text.find("<", position)
        if start < 0:
            break
        end = text.find(">", start + 1)
        if end < 0:
            break
        yield start, end + 1
        position = end + 1


def _slug(heading: str, budget: _Budget) -> str:
    text: list[str] = []
    previous = 0
    for start, end in _html_tags(heading):
        text.append(heading[previous:start])
        previous = end
    text.append(heading[previous:])
    heading = "".join(text)
    pairs = _bracket_pairs(heading)
    # Hide destinations/reference labels while retaining the visible link label.
    hidden: dict[int, int] = {}
    for start, end in pairs.items():
        following = end + 1
        if following < len(heading) and heading[following] == "(":
            parsed = _destination(heading, following + 1, budget)
            closing = _inline_end(heading, parsed[1], budget) if parsed else None
            if closing is not None:
                hidden[following] = closing
        elif following in pairs:
            hidden[following] = pairs[following] + 1
    text = []
    position = 0
    while position < len(heading):
        if position in hidden:
            position = hidden[position]
        else:
            text.append(heading[position])
            position += 1
    heading = "".join(text)
    heading = unescape(_ESCAPE.sub(r"\1", heading)).lower().strip()
    # GitHub retains underscores/hyphens and Unicode letters/numbers/marks.
    return "".join(
        "-" if char.isspace() else char
        for char in heading
        if char.isspace() or char in "_-" or unicodedata.category(char)[0] in "LNM"
    )


def _anchors(text: str, budget: _Budget) -> set[str]:
    anchors: set[str] = set()
    html = _mask_inline_code(text)
    for start, end in _html_tags(html):
        tag = html[start:end]
        position = 0
        while match := _HTML_ANCHOR.search(tag, position):
            position = match.end()
            if position >= len(tag):
                break
            quote = tag[position] if tag[position] in "\"'" else ""
            if quote:
                finish = tag.find(quote, position + 1)
                if finish < 0:
                    break
                value = tag[position + 1:finish]
                position = finish + 1
            else:
                finish = position
                while finish < len(tag) and not tag[finish].isspace() and tag[finish] != ">":
                    finish += 1
                value = tag[position:finish]
                position = finish + 1
            if value:
                anchors.add(unescape(value))
    generated: set[str] = set()
    suffixes: dict[str, int] = {}
    previous = ""
    for line in text.splitlines():
        heading = None
        atx = re.match(r"^ {0,3}#{1,6}(?:[ \t]+(.*?)|[ \t]*)$", line)
        if atx:
            heading = re.sub(r"[ \t]+#+[ \t]*$", "", atx[1] or "")
        elif re.match(r"^ {0,3}(?:=+|-+)[ \t]*$", line) and previous.strip():
            heading = previous.strip()
        if heading is not None:
            base = _slug(heading, budget)
            slug = base
            suffix = suffixes.get(base, 0)
            while slug in generated:
                budget.spend(len(base) + 1)
                suffix += 1
                slug = f"{base}-{suffix}"
            suffixes[base] = suffix
            generated.add(slug)
            anchors.add(slug)
        previous = line if not atx else ""
    return anchors


def _inside(root: Path, path: Path) -> bool:
    try:
        relative = path.relative_to(root)
        return ".." not in relative.parts
    except ValueError:
        return False


class _Repository:
    def __init__(self, root: Path):
        self.root = root.resolve()
        self.documents: dict[Path, _Document | None] = {}
        self.findings: list[Finding] = []
        self.targets: dict[str, tuple[Path | None, bool, bool]] = {}

    def add(self, rule: str, path: str, line: int, message: str, suggestion: str) -> None:
        severity = "warning" if rule in {"LINK005", "LINK006"} else "error"
        self.findings.append(Finding(rule, severity, path, line, message, suggestion))

    def resolve(self, relative: str) -> tuple[Path | None, bool, bool]:
        """Return (actual path, case mismatch, unsafe) without reading outside root."""
        if relative in self.targets:
            return self.targets[relative]
        result = self._resolve(relative)
        self.targets[relative] = result
        return result

    def _resolve(self, relative: str) -> tuple[Path | None, bool, bool]:
        candidate = self.root / relative
        try:
            if not _inside(self.root, candidate.resolve()):
                return None, False, True
        except (OSError, RuntimeError):
            return None, False, True
        current = self.root
        mismatch = False
        # Enumerating each component also detects casing mistakes on Windows.
        for part in Path(relative).parts:
            if part in {"", "."}:
                continue
            if part == "..":
                current = current.resolve().parent
                if not _inside(self.root, current):
                    return None, mismatch, True
                continue
            try:
                children = list(current.iterdir())
                exact = next((child for child in children if child.name == part), None)
                matching = sorted((child for child in children if child.name.casefold() == part.casefold()), key=lambda child: child.name)
                actual = exact or (matching[0] if matching else None)
                if actual is None:
                    return None, mismatch, False
                mismatch = mismatch or exact is None
                if not _inside(self.root, actual.resolve()):
                    return None, mismatch, True
                current = actual
            except (OSError, RuntimeError):
                return None, mismatch, False
        try:
            if not current.exists():
                return None, mismatch, False
        except OSError:
            return None, mismatch, False
        return current, mismatch, False

    def read(self, path: Path) -> _Document | None:
        if path in self.documents:
            return self.documents[path]
        label = path.relative_to(self.root).as_posix()
        self.documents[path] = None
        try:
            resolved = path.resolve(strict=True)
            if not _inside(self.root, resolved):
                self.add("LINK004", label, 1, "Markdown file resolves outside the repository.", "Move the file inside the repository or remove the external symlink.")
                return None
            if not stat.S_ISREG(resolved.stat().st_mode):
                self.add("LINK005", label, 1, "Markdown target is not a regular file.", "Select a regular UTF-8 Markdown file.")
                return None
            with resolved.open("rb") as handle:
                content = handle.read(MAX_MARKDOWN_BYTES + 1)
            if len(content) > MAX_MARKDOWN_BYTES:
                self.add("LINK006", label, 1, "Markdown file exceeds the 1 MiB parsing limit.", "Split the document into smaller Markdown files.")
                return None
            text = content.decode("utf-8-sig")
        except (OSError, UnicodeError, RuntimeError) as error:
            self.add("LINK005", label, 1, f"Cannot read Markdown as UTF-8 ({type(error).__name__}).", "Check the file permissions and save the document as UTF-8.")
            return None
        blocks = _mask_blocks(text)
        try:
            budget = _Budget(len(blocks))
            document = _Document(_links(_mask_inline_code(blocks), budget), _anchors(blocks, budget))
        except _ComplexMarkdown:
            self.add("LINK005", label, 1, "Markdown parsing complexity limit reached.", "Simplify deeply nested or malformed Markdown syntax.")
            return None
        self.documents[path] = document
        return document


def check_links(root: Path, files: list[Path]) -> list[Finding]:
    """Check selected Markdown files and local Markdown anchors, without network IO."""
    repository = _Repository(root)
    for source in sorted(set(files)):
        source = source.absolute()
        if not _inside(repository.root, source):
            # The public caller supplies repository files; do not inspect outsiders.
            repository.add("LINK004", ".", 1, "A selected Markdown file is outside the repository.", "Select only files inside the repository root.")
            continue
        label = source.relative_to(repository.root).as_posix()
        document = repository.read(source)
        if document is None:
            continue
        for link in document.links:
            destination = unescape(_ESCAPE.sub(r"\1", link.destination)).strip()
            if not destination or destination.startswith("//") or _SCHEME.match(destination):
                continue
            raw_path, has_fragment, fragment = destination.partition("#")
            raw_path = raw_path.partition("?")[0]
            decoded_path = unquote(raw_path).replace("\\", "/")
            if "\x00" in decoded_path:
                repository.add("LINK001", label, link.line, "Link contains a NUL byte in its path.", "Use a valid repository-relative file path.")
                continue
            if not decoded_path:
                target, mismatch, unsafe = source, False, False
            else:
                relative = decoded_path.lstrip("/") if decoded_path.startswith("/") else posixpath.join(posixpath.dirname(label), decoded_path)
                target, mismatch, unsafe = repository.resolve(relative)
            if unsafe:
                repository.add("LINK004", label, link.line, f"Local link escapes the repository: {link.destination}", "Point the link to a file within the repository.")
                continue
            if target is None:
                repository.add("LINK001", label, link.line, f"Local link target does not exist: {link.destination}", "Correct the path or add the missing file.")
                continue
            if mismatch:
                actual = target.relative_to(repository.root).as_posix()
                repository.add("LINK003", label, link.line, f"Link filename case differs from the repository: {link.destination}", f"Match the exact filename case: {actual}")
            if has_fragment and fragment and target.suffix.lower() in MARKDOWN_SUFFIXES and target.is_file():
                target_document = repository.read(target)
                anchor = unquote(fragment)
                if target_document is not None and anchor not in target_document.anchors:
                    repository.add("LINK002", label, link.line, f"Markdown anchor does not exist: {link.destination}", "Use an existing heading slug or an explicit HTML id in the target document.")
    return repository.findings
